services:
  - type: web
    name: nombre-del-proyecto
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic
    startCommand: gunicorn nombre_del_proyecto.wsgi:application
